### PR TITLE
- Added geojson files. The files have been validated with https://geo…

### PR DESCRIPTION
**Pull request by yazeed44**
- Added geojson files. The files have been validated with https://geojsonlint.com

- Added generate_geojson.py to generate geojson files based on json files

To generate geojson files, run this in root directory:
    pip install -r requirements.txt
    python generate_geojson.py

As a bonus, the users can see the geojson layers directly from github!

image

### CODE REVIEW

**Comment by aaalsubaie** [comment]
many thanks for this great addition.

**Comment by homaily** [comment]
Hi @yazeed44, thanks for the PR.

Code looks good to me. I've only one comment before merging this PR, `requirements.txt` could be confusing to some users if it's placed in the repo root directory.

Will it be possible to move it to a subdirectory along with `generate_geojson.py` ? An added benefit we can also add `README.md` file next to it with the instructions above for anyone who wants to re-generate the geojson data later on.

**Comment by yazeed44** [comment]
Hello @homaily,

Thanks for your suggestions. I have implemented them in the above commits.

**Comment by homaily** [comment]
Looks good, thanks a lot @yazeed44

**Pull request merged**
